Caught exception! <%= @problem_report.exception_message %>
<% if not @problem_report.signed_in_user_id.blank? %>
    Signed in user id: <%= @problem_report.signed_in_user_id %>
<% else %>
    No signed in user
<% end %>

Exception Class: <%= @problem_report.exception_class %>

Exception Backtrace:
<%= @problem_report.exception_backtrace.join("\n") %>
